# Generated by Django 5.0.14 on 2026-09-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SOLICITUD', 'Solicitud'), ('PETICION', 'Peticion'), ('QUEJA', 'Queja'), ('RECLAMO', 'Reclamo'), ('SUGERENCIA', 'Sugerencia')], default='SOLICITUD', max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=300)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_PROCESO', 'En proceso'), ('RESUELTA', 'Resuelta'), ('CERRADA', 'Cerrada')], default='RECIBIDA', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha'],
            },
        ),
    ]
