# Generated by Django 5.0.14 on 2026-09-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
