# Generated by Django 5.0.14 on 2026-09-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(max_length=500),
        ),
    ]
