# Generated by Django 6.1 on 2026-09-02 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ruta', models.URLField(help_text='URL publica en Supabase Storage', max_length=500)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fechaCarga', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='publicaciones.publicacion')),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
                'ordering': ['-fechaCarga'],
            },
        ),
    ]
