# Generated by Django 5.0.14 on 2026-09-24 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=200)),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('PUBLICACIONES', 'Publicaciones'), ('COMENTARIOS', 'Comentarios'), ('USUARIOS', 'Usuarios')], default='GENERAL', max_length=30)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('fechaGeneracion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fechaGeneracion'],
            },
        ),
    ]
