# Generated by Django 6.1 on 2026-09-02 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField(blank=True, default='', max_length=500)),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('ARCHIVADA', 'Archivada')], default='BORRADOR', max_length=20)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaPublicacion', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='publicaciones.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-fechaPublicacion', '-fechaCreacion'],
            },
        ),
    ]
