# Generated by Django 6.1 on 2026-09-09 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('PUBLICAR', 'Publicar'), ('DESPUBLICAR', 'Despublicar'), ('ARCHIVAR', 'Archivar'), ('APROBADO', 'Aprobar'), ('RECHAZADO', 'Rechazar'), ('LOGIN', 'Iniciar sesion'), ('LOGOUT', 'Cerrar sesion')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('modelo', models.CharField(blank=True, default='', max_length=50)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_actividad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Registros de actividad',
                'ordering': ['-fecha'],
            },
        ),
    ]
